version: '2.1'
services:
  calibrate:
    build:
      context: .
      args:
        - GIT_USER_NAME
        - GIT_USER_EMAIL
    volumes:
      - caches:/root/.cache
      - conda:/opt/conda
      - .:${CALIBRATE_HOME:-/usr/src/calibrate}
    tty:
      true

volumes:
  caches:
  conda:
